apiVersion: v1
metadata:
  name: caddyfile
data:
  Caddyfile: |
    https://digitalocean.andbrant.com:443 {
        templates
        header Content-Type text/plain
        respond "{{.RemoteIP}}"
    }

    http://localhost:8888, http://192.168.2.200:8888, :8888 {
        templates
        header Content-Type text/plain
        respond "{{.RemoteIP}}"
    }

    # https://homeassistant.andbrant.com:443 {
    #     reverse_proxy 10.10.10.3:8123
    # }
kind: ConfigMap
