apiVersion: v1
metadata:
  name: caddyfile
data:
  Caddyfile: "https://digitalocean.andbrant.com:443 {\n    templates\n    header Content-Type
  text/plain\n    respond \"{{.RemoteIP}}\"\n}\n\nhttp://localhost:8888, http://127.0.0.1:8888 {\n    templates\n    header Content-Type
  text/plain\n    respond \"{{.RemoteIP}}\"\n}\n\n# https://homeassistant.andbrant.com:443 {\n#     reverse_proxy
    10.10.10.3:8123\n# }\n\n"
kind: ConfigMap
